### ISSUE TITLE
Puedes integrar githu actions, para tus repos

### ISSUE THREAD

**Issue by Ludocius** [Rocioegrajales/activ2_frontSmartContract#1]
Un saludo Rocio

Espero que estes muy bien

Estaba revisando tu repo, y creo que le vendría muy bien integrar **github** actions, seguro que te va a ayudar en tu proceso de desarrollo de la aplicación.

Un saludo cordial.

**Comment by Rocioegrajales** [comment]
Un gran saludo Luis Fernando!  Espero te encuentres bien.

Muchas gracias por tu sugerencia!  Es muy valiosa, voy a estudiar cómo
hacerlo y lo implemento.

Un abrazo,

Rocío
